### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by xiong1979** [baidu/iot-edge-c-sdk#24]
void iotdm_client_deinit(IOTDM_CLIENT_HANDLE handle)
{
    if (NULL != handle)
    {
        size_t topicSize = CalTopicSize(handle);
        char* topics[topicSize];

这个数组固定大小，编译不通过。

**Comment by xiong1979** [comment]
iot-edge-c-sdk\iothub_client\src下的文件都有这个问题。

**Comment by georgezw** [comment]
编译不过？

Best Regards,
王智

发自我的 iPhone

在 2018年4月22日，18:26，xiong1979 <notifications@github.com<mailto:notifications@github.com>> 写道：


void iotdm_client_deinit(IOTDM_CLIENT_HANDLE handle)
{
if (NULL != handle)
{
size_t topicSize = CalTopicSize(handle);
char* topics[topicSize];

这个数组固定大小，编译不通过。

**Comment by zhaoboc** [comment]
需要为低版本编译器考虑，fix一下。

**Comment by zhaoboc** [comment]
gcc参数-Werror=vla，可以关闭Variable Length Array
https://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html

**Comment by zhaoboc** [comment]
@xiong1979 希望再次跟您确认一下，您是否在使用C89/C90编译器？

**Comment by xiong1979** [comment]
按照说明，使用VS2015。
C语言要求数组定义必须固定大小的。这个在嵌入式平台也编译不过。

**Comment by xiong1979** [comment]
还是编译不过去，问题还在，例如：
SUBSCRIBE_PAYLOAD subscribe[topicSize];

而且iothub_client\src下面的所有文件都有这个问题。

**Comment by zhaoboc** [comment]
@xiong1979 像你说的“C语言要求数组定义必须固定大小的”是值得商榷的。VSVC不是C99编译器。你可以查看文档https://docs.microsoft.com/en-us/cpp/c-language/ansi-conformance，它遵循C90标准。
当然为了兼容性，我们会把语言标准降低到C89/C90。
